### ISSUE TITLE
nxos terminal plugin inconsistently strips whitespace on become

### ISSUE THREAD

**Issue by MrMikeandike** [ansible-collections/cisco.nxos#48] opened 2020-05-05 15:13 UTC
##### SUMMARY

 The nxos terminal plugin's on_become method is inconsistent in when it strips whitespace -- leading to some devices not recognizing that they are enabled.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/terminal/nxos.py
##### ANSIBLE VERSION

```paste below
ansible 2.9.7
```
I've tested it on 2.9.7, 2.9.5, and 2.9.1. I'm relatively certain its an issue on all versions -- and definitely an issue on the current master branch of this repository. 

##### OS / ENVIRONMENT

disclaimer: I'm not strictly a network guy and don't know if this is like super-legacy or not. The OS is a bit irrelevant to the issues I bring up later. 
nexus 7000
BIOS:      version 2.12.0
kickstart: version 6.2(20)
system:   version 6.2(20)

##### STEPS TO REPRODUCE

run any nxos command that impliments on_become method.
In my case, the service account that runs ansible network jobs is automatically enabled through tacacs.

```yaml
- nxos_command:
    commands: show version
  become: yes
```

##### EXPECTED RESULTS

The on_become method should exit right away because the user is already enabled

##### ACTUAL RESULTS

this condition in on_become does not evaluate to true

https://github.com/ansible-collections/cisco.nxos/blob/d4086a4d53d1424e80b34642a613b384a382f2fb/plugins/terminal/nxos.py#L69-L72

the module doesnt really log any of this by default, but the reason turns out to be that there is a space after the '#' in _get_prompt()'s return on my 7k. 
Adding strip() before endswith fixes the issue.

Later in the same method, the check is ran using strip() before endswith
https://github.com/ansible-collections/cisco.nxos/blob/d4086a4d53d1424e80b34642a613b384a382f2fb/plugins/terminal/nxos.py#L98-L102

I see no reason for the inconsistency. I can submit a PR a bit later, but just wanted to make sure there's not some mysterious reason for it being written this way.

**Comment by MrMikeandike** [comment] 2020-05-05 15:20
also, full disclosure, the terminal plugin in its current form wouldn't work in my environment even if the strip() was added due to the prompt not showing as "enable#", but rather showing as "<device name>#". I changed the plugins in my environment to check for "#" rather than "enable#" to compensate. 

Including this just in case it's relevant as to why it's breaking on my device (maybe newer versions of nexus show the prompt differently or something), but I still think making all of the become checks consistent is worth doing.

**Comment by MrMikeandike** [comment] 2020-05-05 15:27
Created PR
#49

**Comment by NilashishC** [comment] 2020-05-26 09:54
@MrMikeandike thank you for adding the PR to fix the issue. It has been merged.

**Comment by NilashishC** [comment] 2020-05-26 10:04
@MrMikeandike Based on the issue description, it seems like you are using a 6.x NX-OS version. This document lists out the platforms and software versions have been certified by Cisco to work with the latest version Ansible: 
https://docs.ansible.com/ansible/latest/network/user_guide/platform_nxos.html#cisco-nexus-platform-support-matrix

It is possible that the enable prompt on your NX-OS 6.2 appliance shows up differently as compared to the supported versions. Would it be possible for you check this on a newer (supported) NX-OS?

cc @mikewiebe

**Comment by MrMikeandike** [comment] 2020-06-01 17:48
@NilashishC 
I Couldn't find a 7k in our environment running 7.3+, but found a 5k running '7.1(5)N1(1)'
Still ran into the same issues as before (trailing whitespace at the end, and prompt is '<hostname>#' rather than 'enable#'

Detailed the test a bit below
Replaced
https://github.com/ansible-collections/cisco.nxos/blob/d4086a4d53d1424e80b34642a613b384a382f2fb/plugins/terminal/nxos.py#L70-L72

with 
```python
self.custom_log('vvvv', "WARNING: entered on_become")

firstprompt = self._get_prompt()
self.custom_log('vvvv', ("WARNING: prompt to check for # BEFORE STRIP: '%s'" % (to_text(firstprompt, errors='surrogate_then_replace')) ) )
firstprompt = firstprompt.strip()
self.custom_log('vvvv', ("WARNING: prompt to check for # AFTER STRIP: '%s'" % (to_text(firstprompt, errors='surrogate_then_replace')) ) )
if firstprompt.endswith(b'enable#'):
    return
```
Just to figure out what the output is.

Output from 7k running 6.3
> WARNING: prompt to check for # BEFORE STRIP: '
the7kHostname# '
 WARNING: prompt to check for # AFTER STRIP: 'the7kHostname#'

output from 5k running 7.1(5)N1(1)

> WARNING: prompt to check for # BEFORE STRIP: '
the5kHostname# '
WARNING: prompt to check for # AFTER STRIP: 'the5kHostname#'

both don't have 'enable#' and both have a space after the '#'.
Perhaps tacacs causes the prompt to show differently?

**Comment by NilashishC** [comment] 2020-11-09 12:45
Apologies for the delay. Both the (platform x NX-OS) combination you mentioned fall outside of the supportability matrix mentioned [here](https://docs.ansible.com/ansible/latest/network/user_guide/platform_nxos.html#cisco-nexus-platform-support-matrix). I confirmed from our partners at Cisco that there maybe a considerable amount of difference between the (platform x NX-OS) you mentioned and the supported ones. However, did you see if it is restricted to just TACACS users or it happens with local users too?

**Comment by NilashishC** [comment] 2021-01-13 11:51
@MrMikeandike Since we haven't any more updates, we will go ahead and close this issue for now. Please feel free to reopen this ticket or reach out to us through the #ansible-network IRC channel or ansible-project mailing list if you wish to discuss this further. Thank you and have a great day ahead!

**Closed by NilashishC** 2021-01-13 11:51 UTC
Labels: needs_info
