### ISSUE TITLE
NXOS - Software Variable, Flat Inventory File.

### ISSUE THREAD

**Issue by rozmusjs** [ansible-collections/cisco.nxos#392] opened 2021-11-24 17:08 UTC
##### SUMMARY

NXOS - Software Variable, Flat Inventory File.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Inventory file or nxos_install_os module

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /home/jrozmus/ansible-network/ansible.cfg
  configured module search path = ['/home/jrozmus/ansible-network/library']
  ansible python module location = /home/jrozmus/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 12 2021, 04:40:35) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

##### COLLECTION VERSION

```paste below
# /home/jrozmus/ansible-network/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 2.7.0

# /home/jrozmus/.local/lib/python3.6/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.4.0

# /usr/local/lib/python3.6/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.4.0

```

##### CONFIGURATION

```paste below
[jrozmus@vmx-jrozm01 ansible-network]$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/collections']
DEFAULT_ACTION_PLUGIN_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/callback']
DEFAULT_FORKS(/home/jrozmus/ansible-network/ansible.cfg) = 100
DEFAULT_HOST_LIST(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/inventories']
DEFAULT_MODULE_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/library']
DEFAULT_ROLES_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/roles']
DEFAULT_SCP_IF_SSH(/home/jrozmus/ansible-network/ansible.cfg) = True
GALAXY_SERVER_LIST(/home/jrozmus/ansible-network/ansible.cfg) = ['release_galaxy']
HOST_KEY_CHECKING(/home/jrozmus/ansible-network/ansible.cfg) = False
INTERPRETER_PYTHON(/home/jrozmus/ansible-network/ansible.cfg) = auto
PERSISTENT_COMMAND_TIMEOUT(/home/jrozmus/ansible-network/ansible.cfg) = 60000000
PERSISTENT_CONNECT_TIMEOUT(/home/jrozmus/ansible-network/ansible.cfg) = 6000

```

##### OS / ENVIRONMENT

NXOS version revisions.

##### STEPS TO REPRODUCE

```yaml
- name: NXOS 3k upgrade
  nxos_install_os:
    system_image_file: "{{ nxos_3k_image }}"
    issu: desired
  when:
    - ansible_net_model == "Nexus3500 C3548P-10GX Chassis" or ansible_net_platform == "N3K-C3548P-10G"
    - nxos_3k_image not in ansible_net_image
  register: upgrade
  tags:
    - nxos-upgrade

```

##### EXPECTED RESULTS

Inventory file (relevant portion):
!
[ld4]
ld4-spinc001
ld4-spinc002
!
[nxos_primary_spines]
ld4-spinc001
!
[nxos_secondary_spines]
ld4-spinc002
!
[nxos_spines:children]
nxos_primary_spines
nxos_secondary_spines
!
[nxos_devices:children]
nxos_spines
!

group_var "nxos_devices" file (relevant configuration)
!
#nxos-upgrade
nxos_3k_image: nxos.9.3.6.bin
!

group_var "ld4"  file (relevant configuration)
!
#nxos-upgrade
nxos_3k_image: nxos.9.3.6.bin
!
ansible-inventory -i inventories/hosts --host ld4-spinc001 | grep bin
"nxos_3k_image": "nxos.9.3.8.bin",

##### ACTUAL RESULTS

```paste below
ansible-inventory -i inventories/hosts --host ld4-spinc001 | grep bin
"nxos_3k_image": "nxos.9.3.6.bin",
```

Question, why the firmware variable "nxos_3k_image" is pulled from "nxos_devices" not "ld4" group_vars? What Ansible rule dictates which variable is used?

**Comment by NilashishC** [comment] 2022-04-25 11:11
Hello @rozmusjs. Apologize for the late response. You can learn about Ansible's variable precedence at 
[docs.ansible.com](doc.ansible.com). I'm sharing a few docs with you here, in case they do not help answering you questions, please feel free to reach out to us at any of the communication channels mentioned in https://docs.ansible.com/ansible/latest/community/communication.html.

- https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
- https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html

Since this is a question and not a bug report or feature request, I'll go ahead and close it. Thank you for your interest in Ansible!

**Closed by NilashishC** 2022-04-25 11:11 UTC
