### ISSUE TITLE
LAG Module not idempotent 

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#293] opened 2021-05-06 19:02 UTC
##### SUMMARY
cisco.nxos.nxos_lag_interfaces module is not idempotent

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_lag_interfaces

##### ANSIBLE VERSION
ansible 2.10.4
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /home/feisa/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or 
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or 
Lesser General Public License (LGPL) Version 2.0. 
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 07.68
 NXOS: version 9.3(6)
  BIOS compile time:  05/18/2020
  NXOS image file is: bootflash:///nxos.9.3.6.bin
  NXOS compile time:  11/9/2020 23:00:00 [11/10/2020 05:00:21]


Hardware
  cisco Nexus9000 C93180YC-EX chassis 
  Intel(R) Xeon(R) CPU  @ 1.80GHz with 24631956 kB of memory.
  Processor Board ID FDO22261SFE

  Device name: tc1-spinc001
  bootflash:   53298520 kB
Kernel uptime is 39 day(s), 2 hour(s), 17 minute(s), 26 second(s)

Last reset at 783791 usecs after Sun Mar 28 11:43:20 2021
  Reason: Reset Requested by CLI command reload
  System version: 9.3(6)
  Service: 

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

##### STEPS TO REPRODUCE
run the following role 
- name: Configure Portchannels  
  cisco.nxos.nxos_lag_interfaces:
    config:
      - name: 101
        members:
          - member: Ethernet1/41
            mode: "{{ item.mode | default('active', true) }}"

  tags:
    - nxos-lag  


##### EXPECTED RESULTS
No Chanages 

##### ACTUAL RESULTS
changed: [tc1-spinc002] => {
    "after": [
        {
            "members": [
                {
                    "member": "Ethernet1/49"
                },
                {
                    "member": "Ethernet1/50"
                }
            ],
            "name": "port-channel5"
        },
        {
            "name": "port-channel6"
        },
        {
            "name": "port-channel7"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/21",
                    "mode": "active"
                }
            ],
            "name": "port-channel21"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/20",
                    "mode": "active"
                }
            ],
            "name": "port-channel22"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/19",
                    "mode": "active"
                }
            ],
            "name": "port-channel23"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/18",
                    "mode": "active"
                }
            ],
            "name": "port-channel24"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/53",
                    "mode": "active"
                }
            ],
            "name": "port-channel100"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/41",
                    "mode": "active"
                }
            ],
            "name": "port-channel101"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/42",
                    "mode": "active"
                }
            ],
            "name": "port-channel102"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/51",
                    "mode": "active"
                }
            ],
            "name": "port-channel103"
        },
        {
            "name": "port-channel104"
        },
        {
            "name": "port-channel105"
        },
        {
            "name": "port-channel106"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/43",
                    "mode": "active"
                }
            ],
            "name": "port-channel107"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/44",
                    "mode": "active"
                }
            ],
            "name": "port-channel108"
        }
    ],
    "before": [
        {
            "members": [
                {
                    "member": "Ethernet1/49"
                },
                {
                    "member": "Ethernet1/50"
                }
            ],
            "name": "port-channel5"
        },
        {
            "name": "port-channel6"
        },
        {
            "name": "port-channel7"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/21",
                    "mode": "active"
                }
            ],
            "name": "port-channel21"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/20",
                    "mode": "active"
                }
            ],
            "name": "port-channel22"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/19",
                    "mode": "active"
                }
            ],
            "name": "port-channel23"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/18",
                    "mode": "active"
                }
            ],
            "name": "port-channel24"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/53",
                    "mode": "active"
                }
            ],
            "name": "port-channel100"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/41",
                    "mode": "active"
                }
            ],
            "name": "port-channel101"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/42",
                    "mode": "active"
                }
            ],
            "name": "port-channel102"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/51",
                    "mode": "active"
                }
            ],
            "name": "port-channel103"
        },
        {
            "name": "port-channel104"
        },
        {
            "name": "port-channel105"
        },
        {
            "name": "port-channel106"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/43",
                    "mode": "active"
                }
            ],
            "name": "port-channel107"
        },
        {
            "members": [
                {
                    "member": "Ethernet1/44",
                    "mode": "active"
                }
            ],
            "name": "port-channel108"
        }
    ],
    "changed": true,
    "commands": [
        "interface Ethernet1/41",
        "channel-group 101 mode active"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "members": [
                        {
                            "member": "Ethernet1/41",
                            "mode": "active"
                        }
                    ],
                    "name": "101"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    }
}


```

**Comment by NilashishC** [comment] 2021-05-10 08:00
@feisa Could you please share the loop var you're iterating through in the "Configure PortChannel" task?

**Comment by feisa** [comment] 2021-05-10 13:41
- name: Configure Portchannels  
  cisco.nxos.nxos_lag_interfaces:
    config:
      - name: "{{ item.lag }}"
        members:
          - member: "{{ item.interface }}"
            mode: "{{ item.mode | default('active', true) }}"
  when:
    - item.lag is defined
  with_items:
    - "{{ trunk_ports }}"
  tags:
    - nxos-lag  


trunk_ports:
  - { interface: Ethernet1/18, allowed: "10,15,17,25,30",        lag: "24", native: "25" }
  - { interface: Ethernet1/19, allowed: "10,15,17,25,30",        lag: "23", native: "25" }
  - { interface: Ethernet1/20, allowed: "10,15,17,25,30",        lag: "22", native: "25" }
  - { interface: Ethernet1/21, allowed: "10,15,17,25,30",        lag: "21", native: "25" }
  - { interface: Ethernet1/41, allowed: "17,20,250-251,300",     lag: "101" }
  - { interface: Ethernet1/42, allowed: "245,250,300",           lag: "102", speed 25000 }
  - { interface: Ethernet1/43, allowed: "30,250-251,300",        lag: "107", speed 25000 }
  - { interface: Ethernet1/44, allowed: "245,250,300",           lag: "108", speed 25000 }
  - { interface: Ethernet1/49,                                   lag: "5" }
  - { interface: Ethernet1/50,                                   lag: "5" }
  - { interface: Ethernet1/51, allowed: "30,66,99,210,250,300",  lag: "103", speed: 40000, no_neg: true }
  - { interface: Ethernet1/52, allowed: "30,66,99,210,250,300",  lag: "104", speed: 40000, no_neg: true }
  - { interface: Ethernet1/54, allowed: "30,66,99,210,250,300", speed: 40000, no_neg: true }

**Comment by NilashishC** [comment] 2021-05-13 06:50
@feisa It seems your variable set combines information from multiple network resources, which is the opposite of what we're trying to accomplish with Resource Modules. The `lag_interfaces` module should only be operated with variables that strictly correspond to the network resource it deals with. Please refer the module documentation and the example I shared to build the source-of-truth for `lag_interfaces` from the targets device and then operate on it.

Since this is not a bug report or a feature request, I will be closing this. If you wish to discuss this further, you can stop by the [ansible-project](https://groups.google.com/g/ansible-project) mailing list, the #ansible-network Freenode IRC channel or the Ansible Network Slack (https://ansiblenetwork.slack.com).

You may also explore [Red Hat Consulting for Ansible](https://www.ansible.com/products/consulting) for professional help in your automation journey.

Thank you very much!

**Closed by NilashishC** 2021-05-13 06:50 UTC
Labels: needs_info
