### ISSUE TITLE
nxos_telemetry

### ISSUE THREAD

**Issue by dsx1123** [ansible-collections/cisco.nxos#124] opened 2020-07-16 19:21 UTC
##### SUMMARY
nxos_telemetry errors out when using cisco.nxos collection

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/virtualenv/ansible/lib/python3.7/site-packages/ansible
  executable location = /root/virtualenv/ansible/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]

cisco.nxos==1.0.1-dev7
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/root/.ansible.cfg) = ['profile_tasks']
DEFAULT_ROLES_PATH(/root/.ansible.cfg) = ['/root/.ansible/collections/ansible_collections/debops/debops/roles', '/etc/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /root/.vault_pass
HOST_KEY_CHECKING(/root/.ansible.cfg) = False

```

##### OS / ENVIRONMENT

nxos version 9.3.4

##### STEPS TO REPRODUCE

```yaml
---
- name: nxos telemetry configration
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Delete Telemetry Configuration
      cisco.nxos.nxos_telemetry:
        state: deleted
      ignore_errors: true
      tags:
        nxos, clear, telemetry
```

##### EXPECTED RESULTS

delete the whole section of telemetry

##### ACTUAL RESULTS

module errors out, but it works if using nxos_telemetry module instead of modules in collection. 

```paste below
TASK [Delete Telemetry Configuration] ************************************************************************************************************************************************************************************************************
task path: /root/workspace/ansible/telemetry/telemetry.yml:6
Thursday 16 July 2020  12:19:45 -0700 (0:00:00.074)       0:00:00.074 *********
<172.25.74.87> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.25.74.87> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-93954ds99kh1 `"&& mkdir /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.2374215-9402-241404546355611 && echo ansible-tmp-1594927186.2374215-9402-241404546355611="` echo /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.2374215-9402-241404546355611 `" ) && sleep 0'
<172.25.74.88> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.25.74.88> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-93954ds99kh1 `"&& mkdir /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.2508032-9403-238589933333465 && echo ansible-tmp-1594927186.2508032-9403-238589933333465="` echo /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.2508032-9403-238589933333465 `" ) && sleep 0'
<172.25.74.61> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.25.74.61> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-93954ds99kh1 `"&& mkdir /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.2929056-9401-185770236952634 && echo ansible-tmp-1594927186.2929056-9401-185770236952634="` echo /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.2929056-9401-185770236952634 `" ) && sleep 0'
<172.25.74.70> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.25.74.70> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-93954ds99kh1 `"&& mkdir /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.300748-9400-227971281150898 && echo ansible-tmp-1594927186.300748-9400-227971281150898="` echo /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.300748-9400-227971281150898 `" ) && sleep 0'
<172.25.74.87> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-93954ds99kh1/ansible-tmp-1594927186.2374215-9402-241404546355611/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 654, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/plugins/action/nxos.py", line 124, in run
    result = super(ActionModule, self).run(task_vars=task_vars)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/plugins/action/network.py", line 48, in run
    result = super(ActionModule, self).run(task_vars=task_vars)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 831, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 215, in _configure_module
    **become_kwargs)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1252, in modify_module
    environment=environment)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1089, in _find_module_utils
    py_module_cache, zf)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/module_common.py", line 880, in recursive_finder
    py_module_names, py_module_cache, zf)
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/module_common.py", line 725, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/module_common.py", line 644, in __init__
    self.get_source()
  File "/root/virtualenv/ansible/lib/python3.7/site-packages/ansible/executor/module_common.py", line 660, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/lib/python3.7/pkgutil.py", line 619, in get_data
    spec = importlib.util.find_spec(package)
  File "/root/virtualenv/ansible/lib/python3.7/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.cisco.nxos.plugins.module_utils.network.nxos.facts.facts.__spec__ is None
fatal: [172.25.74.87]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by NilashishC** [comment] 2020-07-29 09:05
@dsx1123 I am not really sure what's causing this in your environment. The actual code for the telemetry module in 2.9.10 and the collection is identical and hasn't been touched in a while. I tried to reproduce it with Ansible 2.9.10 and cisco.nxos==1.0.1-dev7 but it worked just fine for me. Are you facing this only with the telemetry module or the other nxos modules as well?

**Comment by NilashishC** [comment] 2020-09-17 11:07
@dsx1123 Since we haven't received any updates from your end, we're assuming that this issue is already resolved. As such, we'll be closing this ticket. Please feel free to reopen it in case the issue still persists. You can also reach out to us at #ansible-network on Freenode IRC or through the [ANSIBLE-PROJECT](https://groups.google.com/forum/#!forum/ansible-project) mailing list. Thank you!

**Closed by NilashishC** 2020-09-17 11:07 UTC
Labels: needs_info
