### ISSUE TITLE
Fix idempotent for cisco.nxos.nxos_l2_interfaces

### ISSUE THREAD

**Issue by feisacrabel** [ansible-collections/cisco.nxos#153] opened 2020-09-15 23:13 UTC
##### SUMMARY
The module is not idempotent but if we make the following change 

Original
    def populate_facts(self, connection, ansible_facts, data=None):
        """ Populate the facts for l2_interfaces
        :param connection: the device connection
        :param data: previously collected conf
        :rtype: dictionary
        :returns: facts
        """
        objs = []
        if not data:
            **data = connection.get("show running-config | section ^interface")**

        config = data.split("interface ")
        for conf in config:
            conf = conf.strip()
            if conf:

New
    def populate_facts(self, connection, ansible_facts, data=None):
        """ Populate the facts for l2_interfaces
        :param connection: the device connection
        :param data: previously collected conf
        :rtype: dictionary
        :returns: facts
        """
        objs = []
        if not data:
            **data = connection.get("show running-config all | section ^interface")**

        config = data.split("interface ")
        for conf in config:
            conf = conf.strip()
            if conf:

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_l2_interfaces
##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### STEPS TO REPRODUCE
run the module to configure a vlan

**Comment by NilashishC** [comment] 2020-09-18 04:50
@feisacrabel Could you please share the playbook/task which you're trying out and is not idempotent?

**Comment by feisa** [comment] 2020-09-25 00:10
i think this is it

---
- name: Configure Layer 2 Port Settings 
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface }}"
        description: "{{ item.mode | default( omit) }}"
        duplex: "{{ item.duplex | default( omit) }}"
        enabled: "{{ item.enable | default('yes', true) }}"
        mode: "{{ item.port_type | default( omit) }}"
        mtu: "{{ item.mtu | default( omit) }}"
        speed: "{{ item.speed | default( omit) }}"
  with_items: 
    - "{{ access_ports | union(trunk_ports) }}"
  tags:
    - nxos-interfaces

- name: Configure Layer 3 Port Settings 
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface }}"
        description: "{{ item.mode | default( omit) }}"
        duplex: "{{ item.duplex | default( omit) }}"
        enabled: "{{ item.enable | default('yes', true) }}"
        mode: "{{ item.port_type | default( omit) }}"
        mtu: "{{ item.mtu | default( omit) }}"
        speed: "{{ item.speed | default( omit) }}"
  when: 
    - layer3_ports is defined
  with_items: 
    - "{{ layer3_ports }}"
  tags:
    - nxos-interfaces

**Comment by NilashishC** [comment] 2020-09-25 09:27
The tasks you shared uses nxos_interfaces, but the issue is raised for nxos_l2_interfaces. Is this the correct playbook?

**Comment by feisa** [comment] 2020-09-25 14:35
Thats a bad copy paste


- name: Configure Access Ports
  cisco.nxos.nxos_l2_interfaces:
    config:
    - name: "{{ item.interface }}"
      mode: access
      access:
        vlan: "{{ item.vlan }}"
  with_items: 
    - "{{ access_ports }}"
  tags:
    - nxos-interfaces

- name: Configure Trunk Ports
  cisco.nxos.nxos_l2_interfaces:
    config:
    - name: "{{ item.interface }}"
      mode: trunk
      trunk:
        native_vlan: "{{ item.native }}"
        allowed_vlans: "{{ item.allowed | default(omit) }}"
  with_items: 
    - "{{ trunk_ports }}"
  tags:
    - nxos-interfaces
    - nxos-interfaces-trunks

**Comment by NilashishC** [comment] 2020-09-28 16:37
@feisa Since `mode: access` seems to be default for the target device, this should work fine if you remove the `mode` key from the first task.

**Comment by feisa** [comment] 2020-09-28 16:38
I can try that

**Comment by NilashishC** [comment] 2020-10-19 13:29
@feisa Did it work for you?

**Comment by feisa** [comment] 2020-10-28 19:40
yes this worked thanks

**Comment by NilashishC** [comment] 2020-10-29 14:10
Alright. I'll go ahead and close this issue then. Thank you!

**Closed by NilashishC** 2020-10-29 14:10 UTC
Labels: needs_info
