### ISSUE TITLE
nxos gatherfacts all 

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#295] opened 2021-05-06 22:52 UTC
##### SUMMARY
Hello, 

Part of the nexus parser when running show running-config does not display the full config. I would like an option to instead get the entire config via show running-config all 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
  cisco.nxos.nxos_facts:

##### ADDITIONAL INFORMATION
This allows checks for idempotency to be easier

**Comment by NilashishC** [comment] 2021-05-10 05:41
The network modules by design do not take into account the default values or `show running-config all` and is intended to stay that way. If you require parsing and rendering some of these default values as structured data, you can try out the [cli_parse](https://docs.ansible.com/ansible/latest/collections/ansible/utils/cli_parse_module.html) plugin in ansible.utils collection. It facilitates parsing of cli output or text using a variety of parsers. A detailed guide on how to use it can be found here - https://docs.ansible.com/ansible/latest/network/user_guide/cli_parsing.html.

With that I will be closing this issue. If you wish to discuss this further, please feel free to reach out to us through the following channels mentioned in https://docs.ansible.com/ansible/latest/network/getting_started/network_resources.html#irc-and-slack or the ansible-project mailing list.

Thank you!

**Closed by NilashishC** 2021-05-10 05:41 UTC

**Comment by feisa** [comment] 2021-05-10 13:38
@NilashishC this is a short coming thought process by the module because there are tons of configs now that are not considered default values but are no longer parsed by the normal show running config
