### ISSUE TITLE
nxos_config returns changed: true even though commands is empty

### ISSUE THREAD

**Issue by oh-c** [ansible-collections/cisco.nxos#128] opened 2020-07-27 08:05 UTC
##### SUMMARY
I have a playbook, that removes "port-channel port load-defer" from interfaces on Nexus 9.3.3 based switches.

When running the playbook on one device, result is `"changed": false` but on a similar device it always returns `"changed": true` even if no commands a re sent to the switch.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_config

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /home/oha/foo/ansible.cfg
  configured module search path = ['/home/oha/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oha/venv/ansible/lib64/python3.6/site-packages/ansible
  executable location = /home/oha/venv/ansible/bin/ansible
  python version = 3.6.9 (default, Sep 11 2019, 15:18:54) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
```

##### STEPS TO REPRODUCE
Template

```jinja2
#jinja2: lstrip_blocks: True
{% macro pc_macro(interface) %}
interface {{ interface }}
  {% if load_defer == True %}
  port-channel port load-defer
  {% else %}
  no port-channel port load-defer
  {% endif %}
{% endmacro %}
{% for interface, config in ansible_facts['net_interfaces'].items() %}
  {% if config['type'] is defined and config['type'] == 'Port-Channel' %}
{{ pc_macro(interface) }}
  {%- endif %}
{% endfor %}
```

Playbook
```yaml
- hosts: switch1,switch2
  gather_facts: False
  connection: network_cli

  vars:
    load_defer: False

  tasks:

  - name: Gather facts
    nxos_facts:
      gather_subset: interfaces

  - name: "Set load-defer to {{ load_defer }} on uplink port-channels"
    nxos_config:
      src: load-defer-all-portchannels.j2
      defaults: True
      save_when: modified
```

##### EXPECTED RESULTS
Running the playbook I would expect (as the configuration has already been removed)

```
$ ansible-playbook load-defer.yml -v
TASK [Set load-defer to False on uplink port-channels] ************************************************************************************************************************************Monday 27 July 2020  08:33:12 +0200 (0:00:14.597)       0:00:24.117 ***********
changed: [switch1] => {"changed": false}
changed: [switch2] => {"changed": false}
```

##### ACTUAL RESULTS
```
$ ansible-playbook load-defer.yml -vvvv
TASK [Set load-defer to False on uplink port-channels] ************************************************************************************************************************************Monday 27 July 2020  08:33:12 +0200 (0:00:14.597)       0:00:24.117 ***********
ok: [switch1] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,                                                                                                                                                                                         "authorize": null,                                                                                                                                                                                         "backup": false,                                                                                                                                                                                           "backup_options": null,
            "before": null,
            "defaults": true,
            "diff_against": null,
            "diff_ignore_lines": null,
            "host": null,
            "intended_config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "replace_src": null,
            "running_config": null,
            "save_when": "modified",
            "src": "interface port-channel123\n  no port-channel port load-defer\ninterface port-channel443\n  no port-channel port load-defer\ninterface port-channel1005\n  no port-channel port load-defe
r\ninterface port-channel1006\n  no port-channel port load-defer\ninterface port-channel1007\n  no port-channel port load-defer\ninterface port-channel1001\n  no port-channel port load-defer\ninterface p
ort-channel1002\n  no port-channel port load-defer\ninterface port-channel1003\n  no port-channel port load-defer\n",
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    }
}

changed: [switch2] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "defaults": true,
            "diff_against": null,
            "diff_ignore_lines": null,
            "host": null,
            "intended_config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "replace_src": null,
            "running_config": null,
            "save_when": "modified",
            "src": "interface port-channel153\n  no port-channel port load-defer\ninterface port-channel1035\n  no port-channel port load-defer\ninterface port-channel1037\n  no port-channel port load-defer\ninterface port-channel1031\n  no port-channel port load-defer\ninterface port-channel1030\n  no port-channel port load-defer\ninterface port-channel1033\n  no port-channel port load-defer\ninterface port-channel1039\n  no port-channel port load-defer\ninterface port-channel99\n  no port-channel port load-defer\ninterface port-channel1041\n  no port-channel port load-defer\ninterface port-channel1027\n  no port-channel port load-defer\ninterface port-channel1025\n  no port-channel port load-defer\ninterface port-channel1029\n  no port-channel port load-defer\n",
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    }
}

```

**Comment by NilashishC** [comment] 2020-09-08 12:59
@oh-c I wasn't able to reproduce this issue. However, the task run for `switch2` returning `changed: True` without sending any commands most likely indicates that a `copy running-config startup-config` was executed. This command is not added to the result dictionary, but it influences the value of `changed`.  Observing this behaviour with `save_when: modified` means `running-config` and `startup-config` are not identical for that particular device. 

Can you try running the task without `save_when` on your end to confirm this? Running the task as it is with `--check` should also return `[WARNING]: Skipping command copy running-config startup-config due to check_mode.  Configuration not copied to non-volatile storage`, thereby confirming this explanation.

**Comment by oh-c** [comment] 2020-09-08 13:25
@NilashishC you're right. If I run the playbook with `save_when: modified` i get the warning about skipping saving the configuration.

Ran a playbook to save the config on the device and re-ran my playbook with `save_when: modified` and it works a expected.

**Comment by NilashishC** [comment] 2020-09-08 16:46
@oh-c Alright. I'll be closing this ticket as resolved then. Thanks again!

**Closed by NilashishC** 2020-09-08 16:46 UTC
