### ISSUE TITLE
nxos_interfaces doesn't detect virtual interfaces or virtual interface state

### ISSUE THREAD

**Issue by ajsiersema** [ansible-collections/cisco.nxos#83] opened 2020-06-04 20:13 UTC
##### SUMMARY

Changing the administrative status of a virtual switch interface (SVI or L3 interface) for interfaces in shutdown mode (enabled: no) to enabled: yes doesn't work. 
Changing the configuration for these has no effect:
 ``` 
  system default switchport shutdown
  system default interface-vlan autostate
```

```
show int vl42
   Vlan667 is down (Administratively down), line protocol is down, autostate disabled

show running-config interface Vlan42 all
  interface Vlan42
     no description
     shutdown
```

however without the 'all' the SVI won't show the shutdown whereas regular interfaces will:

```
show running-config | section ^interface
interface Vlan42
   ip address 1.2.3.1/24
interface Ethernet1/1
  shutdown
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_interfaces
ansible/module_utils/network/nxos/facts/interfaces/interfaces.py

'all' is missing from the 2nd show run command for section interface
(included here to show the fix):
```diff
             data = connection.get("show running-config all | incl 'system default switchport'")
-            data += connection.get('show running-config | section ^interface')
+            data += connection.get('show running-config all | section ^interface')

```

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
(no changes)
```

##### OS / ENVIRONMENT

CentOS 8
Cisco Nexus9000 C9300v Chassis
NXOS: version 9.3(3)

##### STEPS TO REPRODUCE

```yaml
- nxos_interfaces:
    config:
      - name: "Vlan42"
        enabled: yes
```

##### EXPECTED RESULTS

'no shutdown' command issues for interfaces that are Administratively down.

##### ACTUAL RESULTS

Interface stays in shutdown, no command issued.

**Comment by NilashishC** [comment] 2020-09-08 14:26
@ajsiersema The system defaults dict is referred to while computing `mode` and `enabled` commands, which eliminates the need for `show running-config all`. However, there was an issue in the sys defaults dict generation, which has been fixed in the collection and [backported](https://github.com/ansible/ansible/pull/69690/files) to ansible/ansible. I can confirm that this works in the latest collection as well as Ansible v2.9.13. Could you please try using either of those and let us know? Thank you!

**Comment by NilashishC** [comment] 2020-10-19 13:31
@ajsiersema Since we haven't heard from you yet, we're assuming that this has been fixed in the latest version of this collection as mentioned above. As such, we'll close this ticket. If you have further questions, please reopen this or reach out to us through the #ansible-network Freenode IRC channel or the ansible-project mailing list.

Thank you!

**Closed by NilashishC** 2020-10-19 13:31 UTC
Labels: needs_info

**Comment by ajsiersema** [comment] 2020-10-19 13:44
Sorry, looks like I missed the message about the backport. I'll run some tests.
Thanks

**Comment by nidebr** [comment] 2021-02-11 11:03
Hi @NilashishC,

I have same issue.

##### ANSIBLE VERSION
```
ansible 2.10.1
```
##### COMPONENT NAME
nxos_interfaces

##### OS / ENVIRONMENT
MacOSX
Cisco Nexus9000 C9300v Chassis
NXOS: version 9.3(6)

I tried with collection release 1.4.0 and 1.4.1-dev2 for same result.

Same test like @ajsiersema for same result SVI interface always "shutdown".

It's work if I make this change on `module_utils/network/nxos/facts/interfaces/interfaces.py` like that : 

Line 60 : 
```diff
- data = connection.get("show running-config | section ^interface")
+ data = connection.get("show running-config all | section ^interface")
```

For information, work fine with old module `nxos_interface` with `admin_state`.

BR
Nick
