### ISSUE TITLE
Using cisco.nxos.nxos_interfaces module to apply default MTU of 1500 not idempotent

### ISSUE THREAD

**Issue by michalstaporek** [ansible-collections/cisco.nxos#246] opened 2021-02-12 13:30 UTC
##### SUMMARY

nxos_interface module NTU setting is not idempotent, the playbook attempts to change the NTU to 1500 even though this is already configured.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_interfaces

##### ANSIBLE VERSION

```
jumpserver:michalstaporek:~/code/inv-ansible-cisco> ansible --version
ansible 2.10.2
  config file = /home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg
  configured module search path = ['/home/local/michalstaporek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, May  6 2020, 12:04:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
COLLECTIONS_PATHS(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = ['/home/local/michalstaporek/code/inv-ansible-cisco']
DEFAULT_ACTION_PLUGIN_PATH(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/action']
DEFAULT_ASK_VAULT_PASS(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = True
DEFAULT_CALLBACK_PLUGIN_PATH(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_HOST_LIST(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = ['/home/local/michalstaporek/code/inv-ansible-cisco/inventory']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/lookup']
DEFAULT_ROLES_PATH(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = ['/home/local/michalstaporek/code/inv-ansible-cisco/roles']
DISPLAY_SKIPPED_HOSTS(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = False
HOST_KEY_CHECKING(/home/local/michalstaporek/code/inv-ansible-cisco/ansible.cfg) = False
```

##### OS / ENVIRONMENT

N77-C7706
  system:    version 7.3(5)D1(1)

##### STEPS TO REPRODUCE

The playbook below should default to '1500' when interface.mtu is not defined.
When run, the playbook tries to configure the MTU to 1500 even though this is already configured.
"commands": ["interface Vlan680", "mtu 1500"]

Default MTU on the device is only visible when you do a "show run all"
switch-n7k1-core1# show run interface Vlan680 all | inc mtu
  mtu 1500

```yaml
    cisco.nxos.nxos_interfaces:
      config:
      - name: "{{ interface }}"
        description: "{{ interface.description }}"
        mtu: "{{ interface.mtu | default('1500') }}"
```

##### EXPECTED RESULTS

The task should check the MTU is already configured to 1500 and complete with OK status instead of attempting to change the configuration

##### ACTUAL RESULTS

The task attempts to change the configuration

```
"commands": ["interface Vlan680", "mtu 1500"]
```

**Comment by NilashishC** [comment] 2021-02-12 14:18
@michalstaporek The nxos_interfaces module operates on the output of `show running-config | section "^interface"`. Since this data does not contain default values (mtu 1500 in this case), any task that attempts to configure one will not be idempotent. This is by design. You can update the task to the following and that should fix this issue.

```yaml
cisco.nxos.nxos_interfaces:
  config:
   - name: "{{ interface }}"
     description: "{{ interface.description }}"
     mtu: "{{ interface.mtu | default(None) }}"
```

As such, we will be closing this ticket. In case you want to discuss this further please feel free to reach out to us either through the #ansible-network Freenode IRC channel or through the [ansible-project](https://groups.google.com/g/ansible-project) mailing list. Thank you for your interest in Ansible!

**Closed by NilashishC** 2021-02-12 14:18 UTC

**Comment by michalstaporek** [comment] 2021-02-12 14:20
That helps, thank you very much
